export const mockItems = [
    {
        thumbnail: "monk.jpg",
        sale:true,
        discountedFrom: 522.50,
        ammount:450.00,
        name: "Blue Partyhat",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
        thumbnail: "arthas.jpg",
        sale:true,
        discountedFrom: 522.50,
        ammount:450.00,
        name: "Blue Partyhat",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
        thumbnail: "alliance.jpg",
        sale:true,
        discountedFrom: 522.50,
        ammount:450.00,
        name: "Blue Partyhat",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
        thumbnail: "dh.jpg",
        sale:true,
        discountedFrom: 522.50,
        ammount:450.00,
        name: "Blue Partyhat",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
        thumbnail: "dk.jpg",
        sale:true,
        discountedFrom: 522.50,
        ammount:450.00,
        name: "Blue Partyhat",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
        thumbnail: "horde.jpg",
        sale:true,
        discountedFrom: 522.50,
        ammount:450.00,
        name: "Blue Partyhat",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
        thumbnail: "mage.jpg",
        sale:true,
        discountedFrom: 522.50,
        ammount:450.00,
        name: "Blue Partyhat",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
        thumbnail: "magni.jpg",
        sale:true,
        discountedFrom: 522.50,
        ammount:450.00,
        name: "Blue Partyhat",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
        thumbnail: "shaman.jpg",
        sale:false,
        name: "Blue Partyhat",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
        thumbnail: "silvanas.jpg",
        sale:false,
        name: "Blue Partyhat",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
        thumbnail: "valeera.jpg",
        sale:false,
        name: "Blue Partyhat",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
        thumbnail: "varian.jpg",
        sale:false,
        name: "Blue Partyhat",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
        thumbnail: "voljin.jpg",
        sale:false,
        name: "Blue Partyhat",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
        thumbnail: "warlock.jpg",
        sale:false,
        name: "Blue Partyhat",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
        thumbnail: "warrior.jpg",
        sale:false,
        name: "Blue Partyhat",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
]